name: Update dynamic repo cards

on:
  push:
    branches: [ "main" ]
    paths:
      - README.md
      - .github/workflows/update_readme.yml
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  TARGET_USER: Khangnguyen01

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate repo cards block
        uses: actions/github-script@v7
        env:
          TARGET_USER: ${{ env.TARGET_USER }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const core = require('@actions/core');

            const username = process.env.TARGET_USER;
            core.info(`Fetching repositories for: ${username}`);

            // Fetch public repos
            const repos = await github.paginate(github.rest.repos.listForUser, {
              username,
              per_page: 100,
              sort: "updated"
            });

            core.info(`Fetched ${repos.length} repos`);

            const filtered = repos.filter(r => !r.fork && !r.archived);
            filtered.sort((a, b) => (b.stargazers_count - a.stargazers_count) || (new Date(b.pushed_at) - new Date(a.pushed_at)));
            const top = filtered.slice(0, 6);

            function card(r) {
              return [
                `  <a href="$${r.html_url}">`,
                `    <img src="https://github-readme-stats.vercel.app/api/pin/?username=Khangnguyen01&repo=$${r.name}&hide_border=true" alt="$${r.name}" />`,
                `  </a>`
              ].join('\n');
            }

            const rows = [
              top.slice(0, 2).map(card).join('\n'),
              top.slice(2, 4).map(card).join('\n'),
              top.slice(4, 6).map(card).join('\n'),
            ];

            const newBlock = `<!-- AUTO-CARDS:START -->
<p align="center">
$${rows[0]}
</p>
<p align="center">
$${rows[1]}
</p>
<p align="center">
$${rows[2]}
</p>
<!-- AUTO-CARDS:END -->`;

            const readmePath = path.join(process.cwd(), "README.md");
            const readme = fs.readFileSync(readmePath, "utf8");

            const start = readme.indexOf("<!-- AUTO-CARDS:START -->");
            const end = readme.indexOf("<!-- AUTO-CARDS:END -->") + "<!-- AUTO-CARDS:END -->".length;

            if (start === -1 || end === -1) {
              core.setFailed("AUTO-CARDS markers not found in README.md");
            } else {
              const updated = readme.slice(0, start) + newBlock + readme.slice(end);
              fs.writeFileSync(readmePath, updated);
              core.info("README updated");
            }

      - name: Commit changes
        run: |
          git config user.name "Nguyen Khang Phuc (bot)"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(readme): auto-update repo cards"
            git push
          fi
